library(dplyr)
library(ggplot2)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(vcd)
library(corrplot)
library(lme4)
library(lubridate)
library(lattice)
library(car)
library(performance)
library(caret)
library(Metrics)

PLD <- read.csv("Data.csv")